### ISSUE TITLE
Russian translation for new UI texts

### ISSUE THREAD

**Issue by Timmeey86** [Timmeey86/FS22_TreeValueInfo#5]
@Gonimy-Vetrom I added more strings to the UI. I will make more changes to the code before I publish a new release, but will not change any text for now, so you can start translating these values already if you feel like it.

Feel free to contact me if you don't understand the full meaning of some of the texts

**Comment by Timmeey86** [comment]
Implemented in #6

**Comment by Gonimy-Vetrom** [comment]
Hello. Can you add a translation for the measurement units?
![Screenshot_8](https://github.com/Timmeey86/FS22_TreeValueInfo/assets/8200153/ec3360bb-27ee-436d-a3b4-5f69ad36084d)

**Comment by Timmeey86** [comment]
I'll try and see how the base game does it. Length and mass is displayed by the base game already so I'm not sure if I can influence that, but I can add it for the liters

**Comment by Gonimy-Vetrom** [comment]
<e k="unit_acre" v="Акры"/>
<e k="unit_acreShort" v="ас"/>
<e k="unit_bale" v="тюк"/>
<e k="unit_bushels" v="Бушели"/>
<e k="unit_bushelsShort" v="bu"/>
<e k="unit_celsius" v="Цельсий"/>
<e k="unit_celsiusShort" v="°C"/>
<e k="unit_cm" v="Сантиметры"/>
<e k="unit_cmShort" v="cm"/>
<e k="unit_cubic" v="Кубические метры"/>
<e k="unit_cubicShort" v="m³"/>
<e k="unit_decimalSymbol" v=","/>
<e k="unit_digitGroupingSymbol" v=" "/>
<e k="unit_dollar" v="Доллары"/>
<e k="unit_dollarShort" v="$"/>
<e k="unit_euro" v="Евро"/>
<e k="unit_euroShort" v="€"/>
<e k="unit_fahrenheit" v="Фаренгейт"/>
<e k="unit_fahrenheitShort" v="°F"/>
<e k="unit_ha" v="Гектары"/>
<e k="unit_haShort" v="га"/>
<e k="unit_kg" v="kg"/>
<e k="unit_km" v="Километры"/>
<e k="unit_kmShort" v="км"/>
<e k="unit_kmh" v="км/ч"/>
<e k="unit_kw" v="кВт"/>
<e k="unit_liter" v="л"/>
<e k="unit_literShort" v="л"/>
<e k="unit_mShort" v="м"/>
<e k="unit_miles" v="Мили"/>
<e k="unit_milesShort" v="ми"/>
<e k="unit_minutesShort" v="мин."/>
<e k="unit_mph" v="миль/ч"/>
<e k="unit_pieces" v="ед."/>
<e k="unit_pound" v="Фунты стерлингов"/>
<e k="unit_poundShort" v="£"/>
<e k="unit_rpmShort" v="об/мин"/>
<e k="unit_timeShort" v="чч:мм"/>
<e k="unit_tonsShort" v="t"/>

**Comment by Gonimy-Vetrom** [comment]
<e k="unit_acre" v="Акры"/>
<e k="unit_acreShort" v="ас"/>
<e k="unit_bale" v="тюк"/>
<e k="unit_bushels" v="Бушели"/>
<e k="unit_bushelsShort" v="bu"/>
<e k="unit_celsius" v="Цельсий"/>
<e k="unit_celsiusShort" v="°C"/>
<e k="unit_cm" v="Сантиметры"/>
<e k="unit_cmShort" v="cm"/>
<e k="unit_cubic" v="Кубические метры"/>
<e k="unit_cubicShort" v="m³"/>
<e k="unit_decimalSymbol" v=","/>
<e k="unit_digitGroupingSymbol" v=" "/>
<e k="unit_dollar" v="Доллары"/>
<e k="unit_dollarShort" v="$"/>
<e k="unit_euro" v="Евро"/>
<e k="unit_euroShort" v="€"/>
<e k="unit_fahrenheit" v="Фаренгейт"/>
<e k="unit_fahrenheitShort" v="°F"/>
<e k="unit_ha" v="Гектары"/>
<e k="unit_haShort" v="га"/>
<e k="unit_kg" v="kg"/>
<e k="unit_km" v="Километры"/>
<e k="unit_kmShort" v="км"/>
<e k="unit_kmh" v="км/ч"/>
<e k="unit_kw" v="кВт"/>
<e k="unit_liter" v="л"/>
<e k="unit_literShort" v="л"/>
<e k="unit_mShort" v="м"/>
<e k="unit_miles" v="Мили"/>
<e k="unit_milesShort" v="ми"/>
<e k="unit_minutesShort" v="мин."/>
<e k="unit_mph" v="миль/ч"/>
<e k="unit_pieces" v="ед."/>
<e k="unit_pound" v="Фунты стерлингов"/>
<e k="unit_poundShort" v="£"/>
<e k="unit_rpmShort" v="об/мин"/>
<e k="unit_timeShort" v="чч:мм"/>
<e k="unit_tonsShort" v="t"/>

**Comment by Gonimy-Vetrom** [comment]
[unit.txt](https://github.com/Timmeey86/FS22_TreeValueInfo/files/14075753/unit.txt)

**Comment by Timmeey86** [comment]
https://github.com/Timmeey86/FS22_TreeValueInfo/commit/4e7145430b122343ff34d667a848bb3e22d28c58 This commit now uses the translated unit for liters. I'm afraid I can't change meters or tons/kilograms
