### ISSUE TITLE
Russian translation for "desired cut length" feature

### ISSUE THREAD

**Issue by Timmeey86** [Timmeey86/FS22_TreeValueInfo#9]
@Gonimy-Vetrom I'll need new translations for a new feature in this branch: https://github.com/Timmeey86/FS22_TreeValueInfo/tree/feature/cut-indication. This has not been merged to master yet, but the texts are stable.

tvi_change_length will be displayed in the F1 menu while input_CYCLE_CUT_INDICATOR will be displayed in the Keybinding menu

I assume you know how to test the mod from a branch locally?

**Comment by Timmeey86** [comment]
Here's a video of what it does: https://www.reddit.com/r/farmingsimulator/comments/1ankpbp/pc_mod_work_in_progress_easy_manual_log_cutting/

**Comment by Gonimy-Vetrom** [comment]
I hope I did everything right

**Comment by Timmeey86** [comment]
@Gonimy-Vetrom I decided to rename the mod since the old mod name is not fitting any longer. I used deepl to come up with a Russian Translation for the new name, does it make sense?

I will not rename the repository for now
